name: iOS CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer

jobs:
  # Job 1: Build & Test
  build-and-test:
    name: Build and Test
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Clean build folder
      run: xcodebuild clean -project HomeCare.xcodeproj -scheme HomeCare
    
    - name: Build
      run: |
        xcodebuild build \
          -project HomeCare.xcodeproj \
          -scheme HomeCare \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
    
    - name: Run tests
      run: |
        xcodebuild test \
          -project HomeCare.xcodeproj \
          -scheme HomeCare \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          -enableCodeCoverage YES \
          | xcpretty --test --color
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/reports/
        retention-days: 30

  # Job 2: SwiftLint
  swiftlint:
    name: SwiftLint
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: swiftlint lint --reporter github-actions-logging

  # Job 3: Security Scan
  security-scan:
    name: Security Scan
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  # Job 4: Code Coverage
  code-coverage:
    name: Code Coverage
    runs-on: macos-14
    needs: build-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
    
    - name: Generate coverage
      run: |
        xcodebuild test \
          -project HomeCare.xcodeproj \
          -scheme HomeCare \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
          -enableCodeCoverage YES \
          -derivedDataPath DerivedData
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./DerivedData/Logs/Test/*.xcresult
        flags: ios
        name: homecare-ios

  # Job 5: Accessibility Audit
  accessibility-audit:
    name: Accessibility Audit
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
    
    - name: Run accessibility tests
      run: |
        xcodebuild test \
          -project HomeCare.xcodeproj \
          -scheme HomeCare \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
          -only-testing:HomeCareTests/AccessibilityTests
    
    - name: Generate accessibility report
      if: always()
      run: echo "Accessibility audit completed"

  # Job 6: Build for different devices
  build-matrix:
    name: Build on ${{ matrix.device }}
    runs-on: macos-14
    strategy:
      matrix:
        device: 
          - 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2'
          - 'platform=iOS Simulator,name=iPhone SE (3rd generation),OS=17.2'
          - 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (6th generation),OS=17.2'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build for ${{ matrix.device }}
      run: |
        xcodebuild build \
          -project HomeCare.xcodeproj \
          -scheme HomeCare \
          -destination '${{ matrix.device }}' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
